import { fetchCourses } from "@/app/lib/db";
import Link from "next/link";
export const metadata = {
    title: "Course Information",
    description: "Generated by create next app",
  };
const Courses = async function() {
  const Courses = await fetchCourses();

  return (
    <div className='container'>
      <h1>Course List</h1>
        <div className="grouping">
          <ul>
              {Courses.map((Courses, index) => (
                <li key={index}>
                  <Link href={`./Courses/${Courses.ID}`}>{Courses.CourseTitle}</Link>
                </li>
              ))}
            </ul>
          </div><br></br>
    </div>
  );
};
export default Courses;
